# Generated by Django 3.1.4 on 2021-01-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_wxid', models.CharField(blank=True, default='', max_length=255, verbose_name='机器人微信id')),
                ('reg', models.CharField(blank=True, default='', max_length=255, verbose_name='命令的正则表达式')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='命令功能等描述')),
                ('scope_wxid', models.CharField(blank=True, default='', max_length=4000, verbose_name='限定微信id范围，多个用,隔开')),
                ('scope_group', models.CharField(blank=True, default='', max_length=4000, verbose_name='限定微信群组id范围，多个用,隔开')),
            ],
            options={
                'verbose_name': '机器人命令表',
                'verbose_name_plural': '机器人命令表',
                'db_table': 'bot_command',
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_wxid', models.CharField(blank=True, default='', max_length=255, verbose_name='机器人微信id')),
                ('val_type', models.CharField(blank=True, default='', max_length=255, verbose_name='配置的值类型（string字符串,array数组,object对象）')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='配置唯一key')),
                ('val', models.CharField(blank=True, default='', max_length=4000, verbose_name='值')),
                ('desc', models.CharField(blank=True, default='', max_length=4000, verbose_name='配置描述')),
            ],
            options={
                'verbose_name': '机器人配置表',
                'verbose_name_plural': '机器人配置表',
                'db_table': 'bot_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=32, verbose_name='用户账号')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='用户密码')),
                ('mobile', models.CharField(blank=True, default='', max_length=11, verbose_name='用户手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='用户邮箱')),
                ('real_name', models.CharField(blank=True, default='', max_length=16, verbose_name='真实姓名')),
                ('id_num', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('nick_name', models.CharField(blank=True, default='', max_length=32, verbose_name='昵称')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='地区')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255, verbose_name='头像')),
                ('open_id', models.CharField(blank=True, default='', max_length=255, verbose_name='微信openid')),
                ('union_id', models.CharField(blank=True, default='', max_length=255, verbose_name='微信unionid')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('is_freeze', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否冻结/是否封号')),
                ('bf_logo_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'A_User_Table',
            },
        ),
    ]
