# Generated by Django 3.1.4 on 2021-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210117_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_wxid', models.CharField(blank=True, default='', max_length=255, verbose_name='机器人微信id')),
                ('activity_type', models.CharField(blank=True, default='', max_length=1000, verbose_name='活动类型')),
                ('from_member_wxid', models.CharField(blank=True, default='', max_length=100, verbose_name='发送人id')),
                ('from_member_nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='发送人微信名称')),
                ('login_req', models.CharField(blank=True, default='', max_length=4000, verbose_name='登录请求信息')),
                ('login_res', models.CharField(blank=True, default='', max_length=4000, verbose_name='登录成功后响应体')),
                ('token', models.CharField(blank=True, default='', max_length=4000, verbose_name='token')),
                ('is_invalid', models.CharField(blank=True, default='否', max_length=10, verbose_name='是否失效（是，否）')),
                ('update_time', models.CharField(blank=True, default='', max_length=20, verbose_name='更新时间')),
                ('create_time', models.CharField(blank=True, default='', max_length=20, verbose_name='创建时间')),
                ('desc', models.CharField(blank=True, default='', max_length=4000, verbose_name='备注')),
            ],
            options={
                'verbose_name': '活动登录信息消息',
                'verbose_name_plural': '活动登录信息消息',
                'db_table': 'bot_activity',
            },
        ),
    ]
