# Generated by Django 3.1.4 on 2021-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botchatactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchatactivity',
            name='login_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='登录用户名'),
        ),
    ]
