# Generated by Django 3.1.4 on 2021-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botchatactivity_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchatactivity',
            name='from_chatroom_nickname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='群组名称'),
        ),
        migrations.AddField(
            model_name='botchatactivity',
            name='from_chatroom_wxid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='群组id'),
        ),
    ]
