# Generated by Django 3.1.4 on 2021-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210304_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchatactivity',
            name='sign_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='上次签到状态（成功,失败）'),
        ),
        migrations.AddField(
            model_name='botchatactivity',
            name='sign_time',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='上次签到时间'),
        ),
    ]
