# Generated by Django 3.1.4 on 2021-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210304_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botchatactivity',
            name='sign_status',
        ),
        migrations.AddField(
            model_name='botchatactivity',
            name='sign_result',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='上次签到结果'),
        ),
    ]
